rule = {
  matches = {
    {
      { "application.process.binary", "equals", "zen" }
    }
  },
  apply_properties = {
    ["stream.restore.prohibit"] = true,
    ["node.pause-on-idle"] = false,
    ["volume"] = 0.20
  }
}
